# Generated by Django 5.1 on 2025-02-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant_doctor',
            name='surname',
        ),
    ]
