# Generated by Django 5.1 on 2025-02-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_remove_assistant_doctor_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant_doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='assistant_doctor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='assistant_doctor',
            name='username',
        ),
    ]
