# Generated by Django 5.1 on 2025-02-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0005_rename_id_doctor_assistant_doctor_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='id_doctor',
            new_name='doctor',
        ),
    ]
