# Generated by Django 5.1 on 2025-02-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0006_rename_id_doctor_availability_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant_doctor',
            options={'ordering': ['created'], 'verbose_name': 'assistant_doctor', 'verbose_name_plural': 'assistants_doctor'},
        ),
        migrations.AlterModelTable(
            name='assistant_doctor',
            table='assistant_doctor',
        ),
    ]
