# Generated by Django 5.1 on 2025-02-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0007_alter_assistant_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rendez_vous.user'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='rendez_vous.user'),
        ),
    ]
