# Generated by Django 5.1 on 2025-02-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0008_alter_availability_doctor_alter_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.doctor'),
        ),
    ]
